themegrill/colormag-pro@free-pro-sync:
  - 404.php
  - archive.php
  - breadcrumb.css
  - changelog.txt
  - comments.php
  - dark.css
  - dark-rtl.css
  - embed-content.php
  - footer.php
  - front-page.php
  - functions.php
  - gulpfile.mjs
  - header.php
  - index.php
  - navigation.php
  - no-results.php
  - page.php
  - postcss.config.js
  - readme.txt
  - search.php
  - searchform.php
  - sidebar.php
  - sidebar-footer.php
  - sidebar-left.php
  - sidebar-two.php
  - sidebar-woocommerce-left.php
  - sidebar-woocommerce-right.php
  - single.php
  - style.css
  - style-editor-block.css
  - style-editor-block-rtl.css
  - style-rtl.css
  - tailwind.config.js
  - theme.json
  - tsconfig.json
  - webpack.config.js
  - woocommerce.css
  - .babelrc
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
  - .gitignore
  - .prettierrc
  - assets/build
  - assets/css
  - assets/fonts
  - assets/img
  - assets/js
  - assets/library
  - assets/sass
  - inc/admin
  - inc/ajax.php
  - inc/base
  - inc/builder-template-tags.php
  - inc/class-breadcrumb-trail.php
  - inc/class-colormag-svg-icons.php
  - inc/class-colormag-walker-page.php
  - inc/colormag-wp-query.php
  - inc/compat
  - inc/compatibility/elementor
  - inc/compatibility/jetpack
  - inc/compatibility/woocommerce
  - inc/core
  - inc/customizer
  - inc/deprecated
  - inc/helper
  - inc/meta-boxes
  - inc/migration
  - inc/template-functions.php
  - inc/template-tags.php
  - inc/widgets
  - page-templates
  - src/dashboard
  - src/meta
  - template-parts
